easy_admin:
  entities:
    - class: App\Entity\Photo
      label: Photos
      form:
        fields:
          - 'title'
          - 'imagePath'
      list:
        fields:
          - 'title'
          - 'imagePath'
      actions:
        - 'new'
        - 'edit'
        - 'delete'
    - class: App\Entity\Dish
      label: Dishes
      list:
        fields:
          - 'id'
          - 'title'
          - 'price'
      form:
        fields:
          - 'title'
          - 'description'
          - 'price'
