easy_admin:
  entities:
    - class: App\Entity\Photo
      label: Photos
      form:
        fields:
          - 'title'
          - 'imagePath'
      list:
        fields:
          - 'title'
          - 'imagePath'
      actions:
        - 'new'
        - 'edit'
        - 'delete'
    - class: App\Entity\Dish
      label: Dishes
      list:
        fields:
          - 'id'
          - 'title'
          - 'price'
      form:
        fields:
          - 'title'
          - 'description'
          - 'price'
    - class: App\Entity\Schedule
      label: Schedules
      list:
        fields:
          - 'day'
          - 'lunchOpening'
          - 'lunchClosing'
          - 'dinnerOpening'
          - 'dinnerClosing'
      form:
        fields:
          - { property: 'day', type: 'text' }
          - { property: 'lunchOpening', type: 'datetime' }
          - { property: 'lunchClosing', type: 'datetime' }
          - { property: 'dinnerOpening', type: 'datetime' }
          - { property: 'dinnerClosing', type: 'datetime' }
      actions:
        - 'new'
        - 'edit'
        - 'delete'
